-- Starter jurisdiction dataset for Permitly.
--
-- IMPORTANT: This is editorial/reference content, not legal advice. Short-term
-- rental ordinances change frequently and vary by neighborhood/zone within a
-- city. Rows marked with an earlier last_verified_on should be re-confirmed
-- against the official source before the product relies on them in production.
-- Treat this file as day-one seed content for the "jurisdictions" admin table,
-- which is meant to be kept current by an operator (see README "Content
-- operations" section).

insert into public.jurisdictions
  (slug, city, state, country, permit_required, permit_name, permit_authority, permit_renewal_months, permit_url,
   tax_name, tax_filing_frequency, tax_authority, tax_url, occupancy_notes, insurance_notes, other_requirements, last_verified_on)
values
  ('new-york-ny', 'New York', 'NY', 'US', true,
   'Short-Term Rental Registration (Local Law 18)', 'Mayor''s Office of Special Enforcement', 12,
   'https://www.nyc.gov/site/specialenforcement/registration-law/registration-rules-and-laws.page',
   'Hotel Room Occupancy Tax', 'quarterly', 'NYC Department of Finance',
   'https://www.nyc.gov/site/finance/business/hotel-room-occupancy-tax.page',
   'Host must be present for the entire stay; whole-unit rentals under 30 days are prohibited outside registered exemptions.',
   'Confirm homeowner/renter policy covers short-term guests; many standard policies exclude it.',
   'Registration is booking-platform gated — unregistered listings cannot legally be booked through major platforms.',
   current_date),

  ('los-angeles-ca', 'Los Angeles', 'CA', 'US', true,
   'Home-Sharing Registration', 'LA City Planning Department', 12,
   'https://planning.lacity.org/home-sharing',
   'Transient Occupancy Tax (TOT)', 'monthly', 'LA Office of Finance',
   'https://finance.lacity.gov/sharing-economy',
   'Primary residence only; hosting capped at 120 nights/year unless extended registration is approved.',
   'Verify short-term rental use is disclosed to your carrier.',
   'Renewal application should be submitted at least 30 days before expiration or the registration lapses.',
   current_date),

  ('san-francisco-ca', 'San Francisco', 'CA', 'US', true,
   'Short-Term Residential Rental Certificate', 'SF Office of Short-Term Rental Administration', 24,
   'https://sfplanning.org/office-short-term-rentals',
   'Transient Occupancy Tax + Tourism Improvement District Assessment', 'quarterly', 'SF Office of the Treasurer & Tax Collector',
   'https://sftreasurer.org/',
   'Host must reside at the unit at least 275 nights/year to remain certified.',
   'Confirm coverage for paying guests; standard renter/homeowner policies often exclude it.',
   'Quarterly hosting activity reports are required in addition to the certificate renewal every two years.',
   current_date),

  ('new-orleans-la', 'New Orleans', 'LA', 'US', true,
   'Short-Term Rental Owner + Operator Permits', 'Short Term Rental Administration (Dept. of Safety & Permits)', 12,
   'https://nola.gov/next/short-term-rental-administration/home/',
   'Occupancy Privilege / Sales Tax', 'monthly', 'City of New Orleans Bureau of Revenue',
   'https://nola.gov/next/finance/',
   'Both an owner permit and an operator permit are required before any rental; non-owner-occupied permits are no longer issued for new applicants.',
   'Fire and life-safety inspection is required at renewal — confirm liability coverage extends to inspected use.',
   'Annual renewal requires a passing fire inspection, current training certificate, and a Healthy Homes Certificate of Compliance.',
   current_date),

  ('honolulu-hi', 'Honolulu', 'HI', 'US', true,
   'Bed & Breakfast / Transient Vacation Unit Registration', 'Dept. of Planning & Permitting', 12,
   'https://www.honolulu.gov/dpp',
   'Transient Accommodations Tax + General Excise Tax', 'monthly', 'Hawaii Department of Taxation',
   'https://tax.hawaii.gov/',
   'B&B category requires the host to reside on-site during the stay; unit and room caps apply.',
   'Confirm policy covers commercial lodging use.',
   'Renew no earlier than 3 months and no later than 1 month before expiration — late renewals can lose grandfathered status.',
   current_date),

  ('austin-tx', 'Austin', 'TX', 'US', true,
   'Short-Term Rental License (Type 1/2/3)', 'Austin Development Services Department', 12,
   'https://www.austintexas.gov/department/short-term-rentals',
   'Hotel Occupancy Tax', 'quarterly', 'City of Austin Financial Services',
   'https://www.austintexas.gov/hotel-occupancy-tax',
   'Type 2 (non-owner-occupied) licenses are capped and subject to a waitlist in many areas — verify current availability.',
   'Confirm coverage for unhosted short-term use.',
   'License type depends on whether the host lives on-site — details vary by zoning; re-verify before relying on this row.',
   '2026-05-01'),

  ('nashville-tn', 'Nashville', 'TN', 'US', true,
   'Short Term Rental Property (STRP) Permit', 'Metro Nashville Codes Department', 12,
   'https://www.nashville.gov/departments/codes/short-term-rental-properties',
   'Hotel Occupancy Privilege Tax', 'monthly', 'Metro Nashville Trustee / TN Dept. of Revenue',
   'https://www.tn.gov/revenue.html',
   'Non-owner-occupied permits are restricted in many residential zoning districts.',
   'Confirm coverage for paying-guest use.',
   'Zoning overlay rules vary block-by-block in Nashville — confirm eligibility before onboarding a property.',
   '2026-05-01'),

  ('miami-beach-fl', 'Miami Beach', 'FL', 'US', true,
   'Business Tax Receipt + Resort Tax Registration', 'City of Miami Beach Finance Dept.', 12,
   'https://www.miamibeachfl.gov/city-hall/finance/',
   'Resort Tax', 'monthly', 'City of Miami Beach Finance Dept.',
   'https://www.miamibeachfl.gov/city-hall/finance/',
   'Short-term rentals under 6 months + 1 day are prohibited in most single-family and many multifamily residential zones — verify the specific address before onboarding.',
   'Confirm coverage explicitly permits short-term/vacation rental use.',
   'Fines for unpermitted short-term rentals in restricted zones are among the steepest in the country — zoning check is essential.',
   '2026-05-01'),

  ('denver-co', 'Denver', 'CO', 'US', true,
   'Short-Term Rental License', 'Denver Excise & Licenses', 12,
   'https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Excise-and-Licenses/Business-Licensing-Portal/All-Business-Types/Short-Term-Rentals',
   'Lodger''s Tax', 'monthly', 'Denver Department of Finance',
   'https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Treasury-Division',
   'Primary residence requirement — host must live at the property.',
   'Confirm coverage for short-term guest use.',
   'License must reference a current Class F or comparable Certificate of Occupancy — check property-specific eligibility.',
   '2026-05-01'),

  ('charleston-sc', 'Charleston', 'SC', 'US', true,
   'Short-Term Rental Permit', 'City of Charleston Livability & Tourism Office', 12,
   'https://www.charleston-sc.gov/1354/Short-Term-Rentals',
   'Accommodations Tax', 'monthly', 'SC Department of Revenue',
   'https://dor.sc.gov/',
   'Non-owner-occupied permits are capped by zone with a waitlist/lottery in high-demand districts.',
   'Confirm coverage for paying-guest use.',
   'Permit category and cap availability depend heavily on the specific zoning district — verify before onboarding.',
   '2026-05-01'),

  ('savannah-ga', 'Savannah', 'GA', 'US', true,
   'Short-Term Vacation Rental Certificate', 'City of Savannah STVR Office', 12,
   'https://www.savannahga.gov/1301/Short-Term-Vacation-Rentals',
   'Hotel/Motel Excise Tax', 'monthly', 'City of Savannah Revenue Department',
   'https://www.savannahga.gov/166/Revenue-Department',
   'Certificates are capped and allocated by lottery in the Historic and Victorian districts.',
   'Confirm coverage for short-term guest use.',
   'A capped market — an existing certificate is tied to the property, confirm it transfers before purchase.',
   '2026-05-01'),

  ('chicago-il', 'Chicago', 'IL', 'US', true,
   'Vacation Rental / Shared Housing Registration', 'Dept. of Business Affairs & Consumer Protection', 12,
   'https://www.chicago.gov/city/en/depts/bacp/supp_info/shared_housing_registration.html',
   'Hotel Accommodations Tax', 'monthly', 'Chicago Department of Finance',
   'https://www.chicago.gov/city/en/depts/fin.html',
   'Some buildings and wards have opted out or added restrictions — check the address-specific list before onboarding.',
   'Confirm coverage for short-term guest use.',
   'A prohibited-buildings list is maintained separately from the base ordinance — check both.',
   '2026-05-01'),

  ('portland-or', 'Portland', 'OR', 'US', true,
   'Accessory Short-Term Rental Permit (Type A/B)', 'Portland Bureau of Development Services', 24,
   'https://www.portland.gov/bds/short-term-rental',
   'Transient Lodging Tax', 'quarterly', 'City of Portland Revenue Division',
   'https://www.portland.gov/revenue',
   'Type A (2 or fewer guest bedrooms, host present) has lighter requirements than Type B.',
   'Confirm coverage for short-term guest use.',
   'Type B permits require a public notice and neighbor notification step before approval.',
   '2026-05-01'),

  ('seattle-wa', 'Seattle', 'WA', 'US', true,
   'Short-Term Rental License + Platform Registration', 'Seattle Finance & Administrative Services', 12,
   'https://www.seattle.gov/license-and-tax-administration/business-licenses-and-taxes/short-term-rentals',
   'Lodging Tax', 'quarterly', 'Washington Dept. of Revenue',
   'https://dor.wa.gov/',
   'Hosts may operate one unit at their primary residence plus one additional unit citywide.',
   'Confirm coverage for short-term guest use.',
   'A separate operator license is required from the platform side — confirm your listing platform holds one.',
   '2026-05-01'),

  ('boston-ma', 'Boston', 'MA', 'US', true,
   'Short-Term Rental Registration', 'Boston Inspectional Services Dept.', 12,
   'https://www.boston.gov/departments/inspectional-services/short-term-rentals',
   'Room Occupancy Excise Tax', 'monthly', 'Massachusetts Department of Revenue',
   'https://www.mass.gov/orgs/massachusetts-department-of-revenue',
   'Registration categories favor owner-occupied and owner-adjacent units; investor-owned units face tighter limits.',
   'Confirm coverage for short-term guest use.',
   'Registration must be renewed annually and displayed on the listing per city rule.',
   '2026-05-01'),

  ('scottsdale-az', 'Scottsdale', 'AZ', 'US', true,
   'Vacation Rental / Short-Term Rental Registration', 'City of Scottsdale', 12,
   'https://www.scottsdaleaz.gov/short-term-rentals',
   'Transaction Privilege Tax (TPT)', 'monthly', 'Arizona Department of Revenue',
   'https://azdor.gov/',
   'State law preempts most local zoning restrictions, but city registration and emergency-contact requirements still apply.',
   'Confirm coverage for short-term guest use.',
   'A state-level TPT license is required in addition to city registration.',
   '2026-05-01'),

  ('palm-springs-ca', 'Palm Springs', 'CA', 'US', true,
   'Vacation Rental Registration Certificate', 'City of Palm Springs Office of Neighborhood Involvement', 12,
   'https://www.palmspringsca.gov/government/departments/planning-services/short-term-vacation-rentals',
   'Transient Occupancy Tax (TOT)', 'monthly', 'City of Palm Springs Finance Dept.',
   'https://www.palmspringsca.gov/government/departments/finance-treasury',
   'Permits are capped citywide with a waitlist; caps and rules vary somewhat by neighborhood.',
   'Confirm coverage for short-term guest use.',
   'A capped market — confirm current waitlist status before assuming a permit is obtainable.',
   '2026-05-01'),

  ('san-diego-ca', 'San Diego', 'CA', 'US', true,
   'Short-Term Residential Occupancy (STRO) License', 'San Diego Development Services Dept.', 12,
   'https://www.sandiego.gov/short-term-residential-occupancy',
   'Transient Occupancy Tax (TOT)', 'quarterly', 'City of San Diego Office of the Treasurer',
   'https://www.sandiego.gov/treasurer',
   'Licenses are tiered (whole-home vs. room rental) with citywide caps allocated via lottery for whole-home licenses.',
   'Confirm coverage for short-term guest use.',
   'Whole-home license availability is capped and allocated through periodic lottery drawings — check current status.',
   '2026-05-01'),

  ('south-lake-tahoe-ca', 'South Lake Tahoe', 'CA', 'US', true,
   'Vacation Home Rental (VHR) Permit', 'City of South Lake Tahoe', 12,
   'https://www.cityofslt.gov/2510/Vacation-Home-Rentals',
   'Transient Occupancy Tax (TOT)', 'quarterly', 'City of South Lake Tahoe Finance Dept.',
   'https://www.cityofslt.gov/',
   'A 2026 ordinance replaced the old 150-foot buffer rule with a citywide cap of 900 VHR permits in residential zones; once the cap is reached, new applicants go on a waitlist.',
   'Confirm coverage for short-term guest use.',
   'Renewal is due within 30 days before expiration — a lapsed permit is void and must be re-applied for from scratch.',
   current_date),

  ('sedona-az', 'Sedona', 'AZ', 'US', true,
   'Short-Term Rental Permit', 'City of Sedona Community Development Dept.', 12,
   'https://www.sedonaaz.gov/your-government/departments/community-development/vacation-rentals',
   'Transaction Privilege Tax (TPT)', 'monthly', 'Arizona Department of Revenue',
   'https://azdor.gov/',
   'Renewal requires a currently valid, unexpired state TPT license on file — an expired TPT license blocks permit renewal.',
   'Confirm coverage for short-term guest use.',
   'Late renewal fees apply as of 2026: $50 if renewed 2-90 days late, $100 if renewed 90+ days late.',
   current_date),

  ('gatlinburg-tn', 'Gatlinburg', 'TN', 'US', true,
   'Tourist Residency Permit', 'City of Gatlinburg', 12,
   null,
   'Sales Tax + Hotel/Motel Tax', 'monthly', 'Tennessee Department of Revenue',
   'https://www.tn.gov/revenue.html',
   'Base permit fee historically around $200 for up to 2 bedrooms plus a per-additional-bedroom charge — confirm the current fee schedule directly with the city.',
   'Proof of property insurance is required at application.',
   'Requires a designated 24/7 local contact, a life-safety self-certification (smoke/CO/fire extinguisher/posted occupancy), and a parking plan.',
   current_date),

  ('key-west-fl', 'Key West', 'FL', 'US', true,
   'Transient Rental License', 'City of Key West + Florida DBPR', 12,
   'https://www.cityofkeywest-fl.gov/',
   'Tourist Development Tax', 'monthly', 'Monroe County Tax Collector',
   null,
   'The city stopped issuing new transient rental licenses in most residential districts back in 2018 — existing grandfathered licenses remain renewable, but new licenses are largely unavailable outside already-licensed zones.',
   'Confirm coverage for short-term guest use.',
   'Annual renewal requires a passing Fire Marshal inspection plus building-code and occupancy-limit verification.',
   current_date),

  ('asheville-nc', 'Asheville', 'NC', 'US', true,
   'Short-Term Rental / Homestay Permit', 'City of Asheville / Buncombe County', 12,
   null,
   'Occupancy Tax', 'monthly', 'Buncombe County Tourism Development Authority',
   null,
   'Whole-house, non-owner-occupied short-term rentals are prohibited in most residential zones inside Asheville city limits; owner-occupied "homestays" are more broadly allowed.',
   'Confirm coverage for short-term guest use.',
   'Rules differ sharply between inside Asheville city limits and unincorporated Buncombe County — confirm the specific parcel''s jurisdiction before assuming eligibility.',
   '2026-05-01'),

  ('newport-ri', 'Newport', 'RI', 'US', true,
   'Short-Term Rental Certificate', 'City of Newport', 12,
   null,
   'Hotel Tax / Sales Tax', 'monthly', 'Rhode Island Division of Taxation',
   'https://tax.ri.gov/',
   'Registration and a designated local contact are required; properties in historic districts can carry additional review.',
   'Confirm coverage for short-term guest use.',
   'Re-verify current caps and zoning rules directly with the city before onboarding — historic-district review can extend approval timelines.',
   '2026-05-01'),

  ('big-bear-lake-ca', 'Big Bear Lake', 'CA', 'US', true,
   'Short-Term Rental Permit', 'City of Big Bear Lake', 12,
   null,
   'Transient Occupancy Tax (TOT)', 'monthly', 'City of Big Bear Lake Finance Dept.',
   null,
   'Permits are capped citywide and tied to the specific parcel — an existing permit does not automatically transfer to a new owner.',
   'Confirm coverage for short-term guest use.',
   'A capped market — confirm current permit availability before assuming one can be obtained for a new property.',
   '2026-05-01'),

  ('traverse-city-mi', 'Traverse City', 'MI', 'US', true,
   'Short-Term Rental Registration', 'City of Traverse City', 12,
   null,
   'Use Tax / Accommodations Tax', 'quarterly', 'Michigan Department of Treasury',
   'https://www.michigan.gov/treasury',
   'Non-owner-occupied rentals face tighter zoning restrictions in several residential districts than owner-occupied hosting.',
   'Confirm coverage for short-term guest use.',
   'Zoning eligibility varies block-by-block — confirm before onboarding a property.',
   '2026-05-01'),

  ('napa-ca', 'Napa', 'CA', 'US', true,
   'Vacation Rental Permit', 'City of Napa Community Development Dept.', 12,
   null,
   'Transient Occupancy Tax (TOT)', 'monthly', 'City of Napa Finance Dept.',
   null,
   'Permits are capped in some residential zones; unincorporated Napa County maintains separate, generally stricter rules.',
   'Confirm coverage for short-term guest use.',
   'Confirm whether the property is inside city limits or unincorporated county — the rules diverge sharply.',
   '2026-05-01'),

  ('nags-head-nc', 'Nags Head', 'NC', 'US', true,
   'Short-Term Rental Registration', 'Town of Nags Head', 12,
   null,
   'Occupancy Tax', 'monthly', 'Dare County Tax Department',
   null,
   'Outer Banks towns each set their own rules independently — Nags Head is generally rental-friendly relative to some neighboring towns, but noise, parking, and occupancy rules can change seasonally.',
   'Confirm coverage for short-term guest use.',
   'Confirm the current town-specific ordinance directly — Outer Banks town rules are not interchangeable with each other.',
   '2026-05-01')
on conflict (slug) do nothing;
